name: Build
on: 
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  GO_VERSION: 1.20.x
  STATICCHECK_VERSION: 2023.1.2

permissions: read-all

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v1
        with:
          egress-policy: block
          disable-telemetry: true
          allowed-endpoints: >
            artifactcache.actions.githubusercontent.com:443
            frsnacprodeus2file1.blob.core.windows.net:443
            github.com:443
            golang.org:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            raw.githubusercontent.com:443
            storage.googleapis.com:443
            sum.golang.org:443

      - name: Check out code into the Go module directory
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v2.4.0
        
      - name: golangci-lint
        uses: golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5 # v2
        with:
          version: latest
          #args: --enable maligned

  build:
    name: Build
    strategy:
      matrix:
        platform: [ubuntu-22.04, windows-2022, macos-12]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v1
        with:
          egress-policy: audit
          disable-telemetry: false
          allowed-endpoints: >
            api.github.com:443
            artifactcache.actions.githubusercontent.com:443
            frsnacprodeus2file1.blob.core.windows.net:443
            github.com:443
            objects.githubusercontent.com:443
            proxy.golang.org:443        
            raw.githubusercontent.com:443
            storage.googleapis.com:443

      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v2.1.5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v2.4.0
        with:
          fetch-depth: 0

      # https://github.com/marketplace/actions/cache
      - name: Cache Go modules
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check and get dependencies
        run: |
          go mod download
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum

      - name: Build
        run: go build -v -trimpath -ldflags="-s -w" ./cmd/bl3auto.go

      - name: Test
        run: go test -v -race ./...
       
      - name: Staticcheck
        uses: dominikh/staticcheck-action@ba605356b4b29a60e87ab9404b712f3461e566dc # v1.1.0
        with:
          version: ${{ env.STATICCHECK_VERSION }}
          install-go: false
          cache-key: ${{ matrix.platform }}
