name: Build
on: 
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  GO_VERSION: 1.19.x
  STATICCHECK_VERSION: 2022.1.3

permissions: read-all

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34 # v1
        with:
          egress-policy: block
          disable-telemetry: true
          allowed-endpoints: >
            artifactcache.actions.githubusercontent.com:443
            frsnacprodeus2file1.blob.core.windows.net:443
            github.com:443
            golang.org:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            raw.githubusercontent.com:443
            storage.googleapis.com:443
            sum.golang.org:443

      - name: Check out code into the Go module directory
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v2.4.0
        
      - name: golangci-lint
        uses: golangci/golangci-lint-action@537aa1903e5d359d0b27dbc19ddd22c5087f3fbc # v2
        with:
          version: latest
          #args: --enable maligned

  build:
    name: Build
    strategy:
      matrix:
        platform: [ubuntu-22.04, windows-2022, macos-12]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34 # v1
        with:
          egress-policy: audit
          disable-telemetry: false
          allowed-endpoints: >
            api.github.com:443
            artifactcache.actions.githubusercontent.com:443
            frsnacprodeus2file1.blob.core.windows.net:443
            github.com:443
            objects.githubusercontent.com:443
            proxy.golang.org:443        
            raw.githubusercontent.com:443
            storage.googleapis.com:443

      - name: Set up Go
        uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # v2.1.5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v2.4.0
        with:
          fetch-depth: 0

      # https://github.com/marketplace/actions/cache
      - name: Cache Go modules
        uses: actions/cache@56461b9eb0f8438fd15c7a9968e3c9ebb18ceff1 # v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check and get dependencies
        run: |
          go mod download
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum

      - name: Build
        run: go build -v -trimpath -ldflags="-s -w" ./cmd/bl3auto.go

      - name: Test
        run: go test -v -race ./...
       
      - name: Staticcheck
        uses: dominikh/staticcheck-action@a3513ade2e5cb8075ba1c1ed1890a989cf0f2aa0 # v1.1.0
        with:
          version: ${{ env.STATICCHECK_VERSION }}
          install-go: false
          cache-key: ${{ matrix.platform }}
