name: ClusterFuzzLite

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: read-all

jobs:
 Fuzzing:
   runs-on: ubuntu-latest
   strategy:
     fail-fast: false
     matrix:
       sanitizer: [address, undefined, memory]

   steps:
   - name: Harden Runner
     uses: step-security/harden-runner@bdb12b622a910dfdc99a31fdfe6f45a16bc287a4 # v1
     with:
       egress-policy: audit

   - name: Build Fuzzers (${{ matrix.sanitizer }})
     id: build
     uses: google/clusterfuzzlite/actions/build_fuzzers@992efa635e18800e2099cb1ea12384033042972c # v1
     with:
       sanitizer: ${{ matrix.sanitizer }}
       upload-build: true

   - name: Run Fuzzers (${{ matrix.sanitizer }})
     id: run
     uses: google/clusterfuzzlite/actions/run_fuzzers@992efa635e18800e2099cb1ea12384033042972c # v1
     with:
       github-token: ${{ secrets.GITHUB_TOKEN }}
       fuzz-seconds: 3600
       sanitizer: ${{ matrix.sanitizer }}

#   - name: Upload Crash
#     uses: actions/upload-artifact@v1
#     if: failure() && steps.build.outcome == 'success'
#     with:
#       name: ${{ matrix.sanitizer }}-artifacts
#       path: ./out/artifacts
