name: ClusterFuzzLite

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: read-all

jobs:
 Fuzzing:
   runs-on: ubuntu-22.04
   strategy:
     fail-fast: false
     matrix:
       sanitizer: [address, undefined, memory]

   steps:
   - name: Harden Runner
     uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v1
     with:
       egress-policy: audit
       disable-telemetry: true

   - name: Build Fuzzers (${{ matrix.sanitizer }})
     id: build
     uses: google/clusterfuzzlite/actions/build_fuzzers@1e163f06cba7820da5154ac9fe1a32d7fe6f73a3 # v1
     with:
       sanitizer: ${{ matrix.sanitizer }}
       upload-build: true

   - name: Run Fuzzers (${{ matrix.sanitizer }})
     id: run
     uses: google/clusterfuzzlite/actions/run_fuzzers@1e163f06cba7820da5154ac9fe1a32d7fe6f73a3 # v1
     with:
       github-token: ${{ secrets.GITHUB_TOKEN }}
       fuzz-seconds: 3600
       sanitizer: ${{ matrix.sanitizer }}

#   - name: Upload Crash
#     uses: actions/upload-artifact@v1
#     if: failure() && steps.build.outcome == 'success'
#     with:
#       name: ${{ matrix.sanitizer }}-artifacts
#       path: ./out/artifacts
