name: Release
on: 
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  GO_VERSION: 1.20.x

permissions: read-all

jobs:
  release:
    name: Release
    strategy:
      matrix:
        platform: [ubuntu-22.04]
    permissions:
      id-token: write
      contents: write
    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v1
        with:
          egress-policy: audit
          disable-telemetry: false
          allowed-endpoints: >
            api.github.com:443
            api.honeycomb.io:443
            artifactcache.actions.githubusercontent.com:443
            frsnacprodeus2file1.blob.core.windows.net:443
            fulcio.sigstore.dev:443
            github.com:443
            golang.org:443
            goreleaser.com:443
            objects.githubusercontent.com:443
            pipelines.actions.githubusercontent.com:443
            raw.githubusercontent.com:443
            rekor.sigstore.dev:443
            storage.googleapis.com:443
            token.actions.githubusercontent.com:443
            toolbox-data.anchore.io:443
            uploads.github.com:443
            v1.fulcio.sigstore.dev:443

      - name: Honeycomb Buildevents
        uses: honeycombio/gha-buildevents@9b348ad6034cb60cde7125f0cb31faa6f6523e28 # v1
        with:
          # Required: a Honeycomb API key - needed to send traces.
          apikey: ${{ secrets.BUILDEVENTS_APIKEY }}

          # Required: the Honeycomb dataset to send traces to.
          dataset: gha-buildevents-bl3auto

          # Required: the job status, this will be used in the post section and sent
          # as status of the trace. Must always be ${{ job.status }}.
          status: ${{ job.status }}

          # Optional: this should only be used in combination with matrix builds. Set
          # this to a value uniquely describing each matrix configuration.
          #matrix-key: ${{ matrix.platform }}

      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v2.1.5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v2.4.0
        with:
          fetch-depth: 0

      # https://github.com/marketplace/actions/cache
      - name: Cache Go modules
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
            
      - name: Cosign
        uses: sigstore/cosign-installer@9e9de2292db7abb3f51b7f4808d98f0d347a8919 # v1.4.1
      
      - name: Generate SBOM
        uses: anchore/sbom-action/download-syft@422cb34a0f8b599678c41b21163ea6088edb2624 # v0.6.0

      # https://goreleaser.com/ci/actions/
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b # v2
        #if: startsWith(github.ref, 'refs/tags/v')
        with:
          version: latest
          args: release -f .goreleaser.yml --clean
        env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.HOMEBREW }}
          COSIGN_EXPERIMENTAL: 1
