name: Release
on: 
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  GO_VERSION: 1.19.x

permissions: read-all

jobs:
  release:
    name: Release
    strategy:
      matrix:
        platform: [ubuntu-22.04]
    permissions:
      id-token: write
      contents: write
    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5 # v1
        with:
          egress-policy: audit
          disable-telemetry: false
          allowed-endpoints: >
            api.github.com:443
            api.honeycomb.io:443
            artifactcache.actions.githubusercontent.com:443
            frsnacprodeus2file1.blob.core.windows.net:443
            fulcio.sigstore.dev:443
            github.com:443
            golang.org:443
            goreleaser.com:443
            objects.githubusercontent.com:443
            pipelines.actions.githubusercontent.com:443
            raw.githubusercontent.com:443
            rekor.sigstore.dev:443
            storage.googleapis.com:443
            token.actions.githubusercontent.com:443
            toolbox-data.anchore.io:443
            uploads.github.com:443
            v1.fulcio.sigstore.dev:443

      - name: Honeycomb Buildevents
        uses: honeycombio/gha-buildevents@9b348ad6034cb60cde7125f0cb31faa6f6523e28 # v1
        with:
          # Required: a Honeycomb API key - needed to send traces.
          apikey: ${{ secrets.BUILDEVENTS_APIKEY }}

          # Required: the Honeycomb dataset to send traces to.
          dataset: gha-buildevents-bl3auto

          # Required: the job status, this will be used in the post section and sent
          # as status of the trace. Must always be ${{ job.status }}.
          job-status: ${{ job.status }}

          # Optional: this should only be used in combination with matrix builds. Set
          # this to a value uniquely describing each matrix configuration.
          #matrix-key: ${{ matrix.platform }}

      - name: Set up Go
        uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # v2.1.5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v2.4.0
        with:
          fetch-depth: 0

      # https://github.com/marketplace/actions/cache
      - name: Cache Go modules
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
            
      - name: Cosign
        uses: sigstore/cosign-installer@9becc617647dfa20ae7b1151972e9b3a2c338a2b # v1.4.1
      
      - name: Generate SBOM
        uses: anchore/sbom-action/download-syft@06e109483e6aa305a2b2395eabae554e51530e1d # v0.6.0

      # https://goreleaser.com/ci/actions/
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757 # v2
        #if: startsWith(github.ref, 'refs/tags/v')
        with:
          version: latest
          args: release -f .goreleaser.yml --rm-dist
        env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.HOMEBREW }}
          COSIGN_EXPERIMENTAL: 1
