name: Release
on: 
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  GO_VERSION: 1.18.x

permissions: read-all

jobs:
  release:
    name: Release
    strategy:
      matrix:
        platform: [ubuntu-latest]
    permissions:
      id-token: write
      contents: write
    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9b0655f430fba8c7001d4e38f8d4306db5c6e0ab # v1
        with:
          egress-policy: audit
          allowed-endpoints: >
            api.github.com:443
            artifactcache.actions.githubusercontent.com:443
            frsnacprodeus2file1.blob.core.windows.net:443
            github.com:443
            goreleaser.com:443
            objects.githubusercontent.com:443
            pipelines.actions.githubusercontent.com:443
            raw.githubusercontent.com:443
            rekor.sigstore.dev:443
            storage.googleapis.com:443
            token.actions.githubusercontent.com:443
            toolbox-data.anchore.io:443
            uploads.github.com:443
            v1.fulcio.sigstore.dev:443     
                  
      - name: Set up Go
        uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2.1.5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.4.0
        with:
          fetch-depth: 0

      # https://github.com/marketplace/actions/cache
      - name: Cache Go modules
        uses: actions/cache@661fd3eb7f2f20d8c7c84bc2b0509efd7a826628 # v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
            
      # Test cosign
      - uses: sigstore/cosign-installer@581838fbedd492d2350a9ecd427a95d6de1e5d01 # v1.4.1
      
      - uses: anchore/sbom-action/download-syft@2ad78246293830258e98b4e707b1fb02d0242828 # v0.6.0

      # https://goreleaser.com/ci/actions/
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@5afacd2427634ace3f2f8a0418a526545c071ffe # v2
        #if: startsWith(github.ref, 'refs/tags/v')
        with:
          version: latest
          args: release -f .goreleaser.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_EXPERIMENTAL: 1
