name: Snyk
on: 
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  security:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-22.04
    
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95 # v1
        with:
          egress-policy: block
          disable-telemetry: true
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            proxy.golang.org:443
            snyk.io:443

      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.4.0
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@7fad562681122205233d1242c3bb39598c5393da # master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
          
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@7fee4ca032ac341c12486c4c06822c5221c76533
        with:
          sarif_file: snyk.sarif
